### ISSUE TITLE
Token discord process.env

### ISSUE THREAD

**Issue by Raffy142** [Kzics/vintedbot#1]
Hi i get this error anytime, you have some solution?
undefined
Started refreshing undefined application (/) commands.
[
  {
    options: [],
    name: 'checkstatus',
    name_localizations: undefined,
    description: 'Check your login status',
    description_localizations: undefined,
    default_permission: undefined,
    default_member_permissions: undefined,
    dm_permission: undefined,
    nsfw: undefined
  },
  {
    options: [],
    name: 'connect',
    name_localizations: undefined,
    description: 'Connect to Vinted',
    description_localizations: undefined,
    default_permission: undefined,
    default_member_permissions: undefined,
    dm_permission: undefined,
    nsfw: undefined
  },
  {
    options: [ [Object], [Object], [Object] ],
    name: 'createtrack',
    name_localizations: undefined,
    description: 'Create track for vinted!',
    description_localizations: undefined,
    default_permission: undefined,
    default_member_permissions: undefined,
    dm_permission: undefined,
    nsfw: undefined
  },
  {
    options: [ [Object] ],
    name: 'lang',
    name_localizations: undefined,
    description: 'Choose your language',
    description_localizations: undefined,
    default_permission: undefined,
    default_member_permissions: undefined,
    dm_permission: undefined,
    nsfw: undefined
  }
]
/home/vintedbot-master/node_modules/discord.js/src/client/Client.js:216
    if (!token || typeof token !== 'string') throw new DiscordjsError(ErrorCodes.TokenInvalid);
                                                   ^

Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/home/vintedbot-master/node_modules/discord.js/src/client/Client.js:216:52)
    at Object.<anonymous> (/home/vintedbot-master/main.js:31:8)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'TokenInvalid'
}

Node.js v18.20.5

**Comment by Kzics** [comment]
Hello the token provided is invalid, you have to change it through the source code

**Comment by Raffy142** [comment]
Where i need replace this?

**Comment by Kzics** [comment]
In the main file there is a client.login. I haven't made a .env file

**Comment by Raffy142** [comment]
i'm getting this errore when i try /connect and inser token, refresh and xcrf token

Error: AxiosError: Request failed with status code 403
    at settle (/home/vintedfunzionante/node_modules/axios/dist/node/axios.cjs:2019:12)
    at Unzip.handleStreamEnd (/home/vintedfunzionante/node_modules/axios/dist/node/axios.cjs:3135:11)
    at Unzip.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/vintedfunzionante/node_modules/axios/dist/node/axios.cjs:4287:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async testLogin (/home/vintedfunzionante/events/interactionCreate.js:115:26)
    at async Object.execute (/home/vintedfunzionante/events/interactionCreate.js:74:17) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
